included:
  - Source

opt_in_rules:
  - anyobject_protocol
  - collection_alignment

line_length:
  warning: 160
  error: 180
  ignores_comments: true
  
file_length:
  warning: 500
  error: 1000
  
disabled_rules:
  - identifier_name