name: MexicanTrain
schemes:
  MexicanTrain:
    build:
      targets:
        MexicanTrain: all
        Tests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MexicanTrain
      targets: 
        - Tests
      commandLineArguments:
        "-isRunningUnitTests YES": true
options:
  bundleIdPrefix: uk.co.cerihughes
packages:
  Madog:
    url: https://github.com/cerihughes/madog
    from: 5.0.1
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
  CombineDataSources:
    url: https://github.com/combineopensource/CombineDataSources
    from: 0.2.5
targets:
  MexicanTrain:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      base:
        INFOPLIST_FILE: Resources/Secret.plist
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.cerihughes.MexicanTrain
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y56955G4Q8
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: mexican-train-dev
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: mexican-train-ad-hoc
    sources:
      - Source
      - path: Resources
        excludes:
          - "Secret.plist"
    dependencies:
      - package: Madog
      - package: SnapKit
      - package: CombineDataSources
    postCompileScripts:
      - script: swiftlint
        name: Swift Lint
    preBuildScripts:
      - script: '"$PROJECT_DIR"/tools/copy-plist.sh'
        name: Increment Build Number
        inputFiles:
          - $PROJECT_DIR/Resources/Info.plist
        outputFiles:
          - $PROJECT_DIR/Resources/Secret.plist
    postBuildScripts:
      - script: '"${PODS_ROOT}/FirebaseCrashlytics/run"'
        name: Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Tests
      - TestResources
    dependencies:
      - target: MexicanTrain