name: MexicanTrain
schemes:
  MexicanTrain:
    build:
      targets:
        MexicanTrain: all
        Tests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MexicanTrain
      targets: 
        - Tests
options:
  bundleIdPrefix: uk.co.cerihughes
packages:
  Madog:
    url: https://github.com/cerihughes/madog
    from: 4.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
targets:
  MexicanTrain:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      INFOPLIST_FILE: Resources/Secret.plist
    sources:
      - Source
      - Resources
    dependencies:
      - package: Madog
      - package: SnapKit
    postCompileScripts:
      - script: swiftlint
        name: Swift Lint
    preBuildScripts:
      - script: '"$PROJECT_DIR"/tools/copy-plist.sh'
        name: Increment Build Number
        inputFiles:
          - $PROJECT_DIR/Resources/Info.plist
        outputFiles:
          - $PROJECT_DIR/Resources/Secret.plist
    postBuildScripts:
      - script: '"${PODS_ROOT}/FirebaseCrashlytics/run"'
        name: Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Tests
      - TestResources
    dependencies:
      - target: MexicanTrain